#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ExamensApp.Resource", IsApplication=true)]

namespace ExamensApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::ExamensApp.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::ExamensApp.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Color0White = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Color1Blue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Color2Red = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Color3Yellow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Color4Green = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Color5Purple = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Color6Cyan = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Color7Gray = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int GameBackground = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int MenuButtonStyle = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int StrikeSpace = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ThreeGame = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000c
			public const int GameOver_EditText = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int GameOver_Header = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int GameOver_NameButton = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int GameOver_QuitButton = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int GameOver_ReplayButton = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int GameOver_Score = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int GameOver_ScoreHeader = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int Game_CurrentColor = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Game_PauseButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Game_PauseText = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int Game_ScoreText = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int Game_StrikeSpace1 = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int Game_StrikeSpace2 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int Game_StrikeSpace3 = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int Game_Table = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int Game_TimerText = 2131034118;
			
			// aapt resource value: 0x7f050026
			public const int Highscore_BackButton = 2131034150;
			
			// aapt resource value: 0x7f050010
			public const int Highscore_Header = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int Highscore_Name01 = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int Highscore_Name02 = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int Highscore_Name03 = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int Highscore_Name04 = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int Highscore_Name05 = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int Highscore_Name06 = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int Highscore_Name07 = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int Highscore_Name08 = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int Highscore_Name09 = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int Highscore_Name10 = 2131034148;
			
			// aapt resource value: 0x7f050013
			public const int Highscore_Score01 = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int Highscore_Score02 = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int Highscore_Score03 = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int Highscore_Score04 = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int Highscore_Score05 = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int Highscore_Score06 = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int Highscore_Score07 = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int Highscore_Score08 = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int Highscore_Score09 = 2131034147;
			
			// aapt resource value: 0x7f050025
			public const int Highscore_Score10 = 2131034149;
			
			// aapt resource value: 0x7f050011
			public const int Highscore_Table = 2131034129;
			
			// aapt resource value: 0x7f050027
			public const int Main_Header = 2131034151;
			
			// aapt resource value: 0x7f050029
			public const int Main_HighScoreButton = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int Main_StartButton = 2131034152;
			
			// aapt resource value: 0x7f05002a
			public const int Three_1 = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int Three_2 = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int Three_3 = 2131034156;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GameOver = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HighScore = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int GameOver_Header = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int GameOver_NameButton = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int GameOver_QuitButton = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int GameOver_ReplayButton = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int GameOver_ScoreHeader = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int Game_PauseButton = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Game_PauseText = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int Game_Score = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int Game_Timer = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040010
			public const int Highscore_BackButton = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int Highscore_Header = 2130968591;
			
			// aapt resource value: 0x7f040005
			public const int Main_BottomText = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int Main_Header = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int Main_HighScoreButton = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int Main_StartButton = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
